### ISSUE TITLE
Unexpected error in provider 'addic7ed'

### ISSUE THREAD

**Issue by chopeta** [pannal/Subliminal.bundle#13]
I am getting this error with Addicted when scanning a single episode for a Serie.
```
2015-09-22 13:37:10,704 (-4f85a490) :  INFO (logger:31) - subliminal_patch.patch_provider_pool: Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>, <Language [pt]>, <Language [es]>])
2015-09-22 13:37:10,705 (-4f85a490) :  INFO (logger:31) - subliminal.api: Initializing provider addic7ed
2015-09-22 13:37:10,706 (-4f85a490) :  INFO (logger:31) - subliminal.providers.addic7ed: Logging in
2015-09-22 13:37:10,710 (-4f85a490) :  INFO (logger:31) - requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): www.addic7ed.com
2015-09-22 13:37:11,609 (-4f85a490) :  DEBUG (logger:21) - requests.packages.urllib3.connectionpool: "POST /dologin.php HTTP/1.1" 302 None
2015-09-22 13:37:11,612 (-4f85a490) :  DEBUG (logger:21) - subliminal.providers.addic7ed: Logged in
2015-09-22 13:37:11,613 (-4f85a490) :  DEBUG (logger:21) - subliminal.providers.addic7ed: Getting show id
2015-09-22 13:37:11,614 (-4f85a490) :  INFO (logger:31) - subliminal.providers.addic7ed: Getting the page of show id 5105, season 1
2015-09-22 13:37:12,337 (-4f85a490) :  DEBUG (logger:21) - requests.packages.urllib3.connectionpool: "GET /show/5105?season=1 HTTP/1.1" 304 0
2015-09-22 13:37:12,340 (-4f85a490) :  ERROR (logger:31) - subliminal_patch.patch_provider_pool: Unexpected error in provider 'addic7ed', discarding it, because of: Traceback (most recent call last):
  File "/mnt/cache/apps/PMS/Library/Application Support/Plex Media Server/Plug-ins/Subliminal.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 170, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/mnt/cache/apps/PMS/Library/Application Support/Plex Media Server/Plug-ins/Subliminal.bundle/Contents/Libraries/Shared/subliminal/providers/addic7ed.py", line 256, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/mnt/cache/apps/PMS/Library/Application Support/Plex Media Server/Plug-ins/Subliminal.bundle/Contents/Libraries/Shared/subliminal/providers/addic7ed.py", line 225, in query
    match = series_year_re.match(soup.select('#header font')[0].text.strip()[:-10])
IndexError: list index out of range

2015-09-22 13:37:12,342 (-4f85a490) :  INFO (logger:31) - subliminal_patch.patch_provider_pool: Listing subtitles with provider 'tvsubtitles' and languages set([<Language [en]>, <Language [pt]>, <Language [es]>])
2015-09-22 13:37:12,343 (-4f85a490) :  INFO (logger:31) - subliminal.api: Initializing provider tvsubtitles```

**Comment by pannal** [comment]
This is something I didn't encounter yet. Looking into it. Maybe a provider fix is needed by subliminal.

**Comment by pannal** [comment]
Yeah, that's not related to my fork as far as I can tell, but I'll try to fix that. Thanks for reporting!

**Comment by pannal** [comment]
I wasn't really able to reproduce this issue. Please test the new beta release to see if this still persists.

If it does, I'll need more information about the local filename, local show name etc.

**Comment by pannal** [comment]
OK this may be because addic7ed throttled your connection attempts. I've just had that error. If you can live with it, you may try the new option "Addic7ed: Use random user agents (should not be necessary)". It may help.
